sudo: false
services:
- docker
language: rust
rust:
- nightly
cache: cargo
before_script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker pull clux/muslrust:nightly
script:
- make build
after_success:
- make tag-latest
- make tag-semver
after_script:
- docker logout
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: "Q3EB8FYUSuk6yP1WyyDmyDH1V4Uow6ad/dWfEN7chQBntm6Tskr9oQCRoZ8PBNARFDOqH+Uy7O0xkJ5q3AM5thRtWiyHp+j63ihPYonbKi0bZT99DO2K4de/vw9S4CTMobS3iLB6HgFHg9YLfMAWGtJIFGRDz1D0WpURPy4ikm+9v31U1E+sk+Y07+sSoE+6svtCNuSAhXI5/r6EPYHgpGFfLOs1wkcFEL+D5k2NJBr5MIJXT+snxS7sm7D/ePk2tcnQnVYGEGQUF9/pt7Dzev9rsMxBfWBQYK30fByT3rh+gtz2XCXRefKEBlCdqbAj5DCnFcH/mKM0NJ/2YgIvGQKA/TKAV5VsBtc6mEQrPhNRo/JUtGWws3gx23bK3ZYayq1/SRdPBb+zh4MhIat94rORo8UUDi94znluhuh+0Uo2G4Ux2e1ii+q7Zn9FKIpBMi+GGDFNMKbCb5on4+/5jdkwXOITY48ojx7AVZcMWaTU6VIDzGvME4YapSZ1T1fqnxPZwc76Yv2CYKF4kLU+etrnpg6PwF+l5mRlyhMc/1FBgJscNcuCzPfTTB8DwGteLL7vtmqP66R3dsGLMtpim/NW3uG3bEnmSyEedsjKRTeBSlacj+m2r9ZSWOkkO6208aWqT9/9Z2aCP2ytoZX7VLzVjY0Jnu5h6uizmXz+CWI="
